sudo: false
# We use stack, and so don't rely on Travis’ default Haskell support
language: generic
os:
  - osx # Build on OS X (that's the only system I currently care for)
addons:
  # Dependencies for GHC
  apt:
    packages:
      - libgmp-dev
before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/osx-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
  # Build dependencies
  - stack --no-terminal --install-ghc test --only-dependencies
script:
  # Build package, docs, and test it
  - stack --no-terminal test --haddock --no-haddock-deps
cache:
  directories:
  - $HOME/.stack
